DROP DATABASE IF EXISTS sisaluno;

CREATE DATABASE sisaluno;

USE sisaluno;

CREATE TABLE aluno(
id SMALLINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
idade SMALLINT, 
datanascimento DATE,
endereco VARCHAR(100) NOT NULL,
estatus VARCHAR(20),
curso VARCHAR(40) NOT NULL, 
turma CHAR(4)
);

CREATE TABLE professor(
id SMALLINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL,
idade SMALLINT,
datanascimento DATE,
endereco VARCHAR(100) NOT NULL,
estatus BOOL,
email VARCHAR(150) NOT NULL
);

CREATE TABLE disciplina(
id SMALLINT AUTO_INCREMENT PRIMARY KEY,
nomedisciplina VARCHAR(100) NOT NULL,
ch VARCHAR(3) NOT NULL,
semestre VARCHAR(5),
idprofessor SMALLINT
);

SELECT * FROM aluno;
SELECT * FROM professor;
SELECT * FROM disciplina;
